import PersonAdd from '@mui/icons-material/PersonAdd';
import Settings from '@mui/icons-material/Settings';
import Logout from '@mui/icons-material/Logout';
import WalletIcon from '@mui/icons-material/AccountBalanceWallet';
import NotificationsIcon from '@mui/icons-material/Notifications';
import CakeTwoToneIcon from '@mui/icons-material/CakeTwoTone';
import CelebrationTwoToneIcon from '@mui/icons-material/CelebrationTwoTone';
import GroupAddTwoToneIcon from '@mui/icons-material/GroupAddTwoTone';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import HourglassTopIcon from '@mui/icons-material/HourglassTop';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import InboxIcon from '@mui/icons-material/MoveToInbox';
import MailIcon from '@mui/icons-material/Mail';
import Search from '@mui/icons-material/Search';
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward';
import ShoppingCartIcon from '@mui/icons-material/ShoppingCart';
import PeopleIcon from '@mui/icons-material/People';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';
import HomeIcon from '@mui/icons-material/Home';
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong';
import EventAvailableIcon from '@mui/icons-material/EventAvailable';

export const SettingsIcon = Settings;
export const LogoutIcon = Logout;
export const Wallet = WalletIcon;
export const Notifications = NotificationsIcon;
export const PersonAddIcon = PersonAdd;
export const CakeTwoTone = CakeTwoToneIcon;
export const CelebrationTwoTone = CelebrationTwoToneIcon;
export const GroupAddTwoTone = GroupAddTwoToneIcon;
export const ChevronLeft = ChevronLeftIcon;
export const HourglassTop = HourglassTopIcon;
export const ChevronRight = ChevronRightIcon;
export const Inbox = InboxIcon;
export const Mail = MailIcon;
export const SearchIcon = Search;
export const ArrowUpward = ArrowUpwardIcon;
export const ShoppingCart = ShoppingCartIcon;
export const People = PeopleIcon;
export const AttachMoney = AttachMoneyIcon;
export const Home = HomeIcon;
export const ReceiptLong = ReceiptLongIcon;
export const EventAvailable = EventAvailableIcon;

