"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
var gql = require('apollo-server').gql;
var typeDefs = gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  type Diet {\n    id: ID!\n    name: String!\n    calories: Int!\n    fat: Float!\n    carbs: Float!\n    protein: Float!\n  }\n\n  type Consultant {\n    id: ID!\n    name: String!\n    age: Int!\n    gender: String!\n    plan: String!\n    status: String!\n  }\n\n  type Appointment {\n    id: ID!\n    name: String!\n    date: String!\n    time: String!\n    location: String!\n    dietname: String!\n  }\n\n  type Query {\n    diets: [Diet!]!\n    consultants: [Consultant!]!\n    appointments: [Appointment!]!\n    options: [String!]!\n    dietOptions: [String!]!\n  }\n\n  type Mutation {\n    addDiet(id: ID!, name: String!, calories: Int!, fat: Float!, carbs: Float!, protein: Float!): Diet!\n    deleteDiet(id: ID!): Diet\n    addConsultant(id: ID!, name: String!, age: Int!, gender: String!, plan: String!, status: String!): Consultant!\n    deleteConsultant(id: ID!): Consultant\n    addAppointment(id: ID!, name: String!, date: String!, time: String!, location: String!, dietname: String!): Appointment!\n    deleteAppointment(id: ID!): Appointment\n    login(email: String!, password: String!): LoginResponse!\n  }\n\n  type LoginResponse {\n    success: Boolean!\n    message: String!\n  }\n"], ["\n  type Diet {\n    id: ID!\n    name: String!\n    calories: Int!\n    fat: Float!\n    carbs: Float!\n    protein: Float!\n  }\n\n  type Consultant {\n    id: ID!\n    name: String!\n    age: Int!\n    gender: String!\n    plan: String!\n    status: String!\n  }\n\n  type Appointment {\n    id: ID!\n    name: String!\n    date: String!\n    time: String!\n    location: String!\n    dietname: String!\n  }\n\n  type Query {\n    diets: [Diet!]!\n    consultants: [Consultant!]!\n    appointments: [Appointment!]!\n    options: [String!]!\n    dietOptions: [String!]!\n  }\n\n  type Mutation {\n    addDiet(id: ID!, name: String!, calories: Int!, fat: Float!, carbs: Float!, protein: Float!): Diet!\n    deleteDiet(id: ID!): Diet\n    addConsultant(id: ID!, name: String!, age: Int!, gender: String!, plan: String!, status: String!): Consultant!\n    deleteConsultant(id: ID!): Consultant\n    addAppointment(id: ID!, name: String!, date: String!, time: String!, location: String!, dietname: String!): Appointment!\n    deleteAppointment(id: ID!): Appointment\n    login(email: String!, password: String!): LoginResponse!\n  }\n\n  type LoginResponse {\n    success: Boolean!\n    message: String!\n  }\n"])));
exports["default"] = typeDefs;
var templateObject_1;
